### ISSUE TITLE
Could not load type 'Avalonia.IAvaloniaObject

### ISSUE THREAD

**Issue by tomlm** [jp2masa/Avalonia.Flexbox#3]
09:18:03.545 [Error] 7208 UpdateXamlResult error
System.Xaml.XamlException: 'Internal compiler error while transforming node xml!!clr-namespace:Avalonia.Flexbox;assembly=Avalonia.Flexbox:FlexPanel:
System.TypeLoadException: **Could not load type 'Avalonia.IAvaloniaObject' from** assembly 'Avalonia.Base, Version=11.0.5.0, Culture=neutral, PublicKeyToken=c8d484a7012f9a8b'.
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, StackCrawlMarkHandle stackMark, ObjectHandleOnStack assemblyLoadContext, ObjectHandleOnStack type, ObjectHandleOnStack keepalive)
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext)
   at System.Type.GetType(String typeName)
   at XamlX

This is using Avalonia 11.0.5 and the package via nuget

**Comment by jp2masa** [comment]
The `FlexPanel` was moved to [Avalonia.Labs](https://github.com/AvaloniaUI/Avalonia.Labs). The nuget package is [Avalonia.Labs.Panels](https://www.nuget.org/packages/Avalonia.Labs.Panels).

**Comment by tomlm** [comment]
sweet!
